
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/bicycleshop.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php


  php:
    build: docker/php
    volumes:
      - .:/app
    working_dir: /app


  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
